{
 "title": "Temperatur",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "2. Stock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lara",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "helius",
     "rawSql": "SELECT \n  AVG(temperature_c) \nFROM \n  temperature_readings \nWHERE \n  sensor_id = 'shelly_ht_floor2' \n  AND temperature_c IS NOT NULL  \nLIMIT 1"
    },
    {
     "dataset": "helius",
     "rawSql": "SELECT \n  AVG(humidity_pct) \nFROM \n  temperature_readings \nWHERE \n  sensor_id = 'shelly_ht_floor2'\n  AND humidity_pct IS NOT NULL   \nLIMIT 1"
    }
   ]
  },
  {
   "title": "Verlauf heute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "helius",
     "rawSql": "SELECT\n  $__timeGroupAlias(recorded_at, $__interval),\n  AVG(temperature_c) AS temperature_c\nFROM\n  temperature_readings\nWHERE\n  sensor_id = 'shelly_ht_floor2'\n  AND $__timeFilter(recorded_at)\n  AND temperature_c IS NOT NULL  \nGROUP BY 1\nORDER BY 1 ASC\n"
    },
    {
     "dataset": "helius",
     "rawSql": "SELECT\n  $__timeGroupAlias(recorded_at, $__interval),\n  AVG(humidity_pct) AS humidity_pct\nFROM\n  temperature_readings\nWHERE\n  sensor_id = 'shelly_ht_floor2'\n  AND $__timeFilter(recorded_at)\n  AND humidity_pct IS NOT NULL  \nGROUP BY 1\nORDER BY 1 ASC"
    }
   ]
  },
  { "title": "1. Stock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Zimmer klein",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rehalp92\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"firstfloor_temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field:\"Temperatur\" }))"
    },
    {
     "query": "from(bucket: \"rehalp92\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"firstfloor_humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field:\"Feuchtigkeit\" }))"
    }
   ]
  },
  {
   "title": "Verlauf heute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"rehalp92\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"firstfloor_temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field:\"Temperatur\" }))"
    },
    {
     "query": "from(bucket: \"rehalp92\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"firstfloor_humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field:\"Feuchtigkeit\" }))"
    }
   ]
  },
  {
   "title": "Timo",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rehalp92\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"timo_temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tC\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field:\"Temperatur\" }))"
    },
    {
     "query": "from(bucket: \"rehalp92\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"timo_humidity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rh\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field:\"Feuchtigkeit\" }))"
    }
   ]
  },
  {
   "title": "Verlauf heute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"rehalp92\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"timo_temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tC\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field:\"Temperatur\" }))"
    },
    {
     "query": "from(bucket: \"rehalp92\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"timo_humidity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rh\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field:\"Feuchtigkeit\" }))"
    }
   ]
  },
  { "title": "EG", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Wohnzimmer",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rehalp92\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"living-room_temperature\" and r[\"_field\"] == \"tC\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field:\"Temperatur\" }))"
    },
    {
     "query": "from(bucket: \"rehalp92\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"living-room_humidity\" and r[\"_field\"] == \"rh\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field:\"Feuchtigkeit\" }))"
    }
   ]
  },
  {
   "title": "Verlauf heute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"rehalp92\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"living-room_temperature\" and r[\"_field\"] == \"tC\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field:\"Temperatur\" }))"
    },
    {
     "query": "from(bucket: \"rehalp92\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"living-room_humidity\" and r[\"_field\"] == \"rh\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field:\"Feuchtigkeit\" }))"
    }
   ]
  },
  { "title": "Keller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Keller",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rehalp92\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"celler_room_temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field:\"Temperatur\" }))"
    },
    {
     "query": "from(bucket: \"rehalp92\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"celler_room_humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field:\"Feuchtigkeit\" }))"
    }
   ]
  },
  {
   "title": "Verlauf heute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"rehalp92\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"celler_room_temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field:\"Temperatur\" }))"
    },
    {
     "query": "from(bucket: \"rehalp92\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"celler_room_humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field:\"Feuchtigkeit\" }))"
    }
   ]
  }
 ]
}